# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5Z7KvL_FE1hmu4_A9anJC8fneDZWEL5
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

try:
  dados = pd.read_csv("compras.csv")
except:
  dados = pd.DataFrame({"produto": [], "preço": []})
  dados.to_csv("compras.csv", index=False)

st.title("Controle de Compras")

orcamento = st.number_input ("Orçamento:", min_value = 0.0)
total = dados ["preço"].sum() if not dados.empty else 0

with st.form("nova_compra"):
  produto = st.text_input("Adicione aqui o seu produto")
  preco = st.number_input("Indique o preço", min_value = 0.0)

  if st.form_submit_button("Adicionar"):
    if preco <= (orcamento-total):
      nova_linha = pd.DataFrame({"produto": [produto], "preço": [preco]})
      dados = pd.concat
      dados.to_csv("compras.csv", index=False)
    else:
      st.error("Não tem orçamento suficiente")

  if orcamento > 0:
    fig, ax=plt.subplots(figsize=(8,8))
    produtos = dados["produto"].tolist()
    valores = dados["preço"].tolist()
    restante = orcamento - total
    if restante > 0:
        produtos.append("Disponível")
        valores.append(restante)

    plt.pie(valores, labels=produtos, autopct='%1.1f%%', pctdistance=0.85)
    plt.title(f"Orçamento: {orcamento}€")
    centro = plt.Circle((0, 0), 0.70, fc='white')
    ax.add_artist(centro)
    st.pyplot(fig)

  st.dataframe(dados)
  st.write(f"Total gasto: {total}€")
  st.write(f"Resta: {orcamento - total}€")

